# Generated by Django 3.0.7 on 2020-07-01 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_name', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_designation', models.CharField(max_length=50)),
                ('admin_phone', models.CharField(max_length=15)),
                ('admin_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birthdate', models.DateField()),
                ('customer_address', models.CharField(max_length=254)),
                ('customer_password', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('DS_id', models.AutoField(primary_key=True, serialize=False)),
                ('DS_start_time', models.TimeField()),
                ('DS_stop_time', models.TimeField()),
                ('DS_capacity', models.IntegerField(default=15)),
                ('DS_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('pharmacy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pharmacy_address', models.CharField(max_length=254)),
                ('owner_name', models.CharField(max_length=100)),
                ('pharmacy_name', models.CharField(max_length=100)),
                ('pharmacy_reg_id', models.CharField(max_length=100)),
                ('employee_password', models.CharField(max_length=100)),
                ('pharmacy_rating', models.FloatField(max_length=3, null=True)),
                ('pharmacy_rating_count', models.PositiveIntegerField(default=0)),
                ('employee_email', models.EmailField(max_length=254)),
                ('employee_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('OP', 'Processing'), ('OTW', 'On the way'), ('DV', 'Medicine Delivered')], default='OP', max_length=3)),
                ('rating', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.Customer')),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.Delivery')),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pres_status', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.Customer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('med_name', models.CharField(max_length=200)),
                ('med_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('med_price', models.FloatField(max_length=10)),
                ('med_quantity', models.PositiveIntegerField()),
                ('med_status', models.CharField(choices=[('MP', 'Must be Prescribed'), ('MNP', 'Must not be Prescribed')], default='MP', max_length=3)),
                ('med_catagory', models.CharField(choices=[('A', 'General and unspecified'), ('B', 'Blood, blood forming organs, lymphatics, spleen'), ('D', 'Digestive'), ('F', 'Eye'), ('H', 'Ear'), ('K', 'Circulatory'), ('L', 'Musculoskeletal'), ('N', 'Neorological'), ('P', 'Psychological'), ('R', 'Respiratory'), ('S', 'Skin'), ('T', 'Endocrine, metabolic and nutritional'), ('U', 'Urology'), ('W', 'Pregnancy, childbirth, family planning'), ('X', 'Female genital system and breast'), ('Y', 'Male genital system'), ('Z', 'Social problems')], default='A', max_length=2)),
                ('med_generic', models.CharField(max_length=100)),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=10)),
                ('coupon_amount', models.IntegerField()),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.Inventory')),
            ],
        ),
    ]
