# Generated by Django 3.0.7 on 2020-07-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0002_auto_20200717_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='med_ids',
        ),
    ]
