# Generated by Django 3.0.7 on 2020-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0003_remove_order_med_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='med_ids',
            field=models.ManyToManyField(to='medbot_app.Inventory'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
