# Generated by Django 3.0.7 on 2020-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0004_auto_20200723_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('BKS', 'Bkash'), ('RKT', 'Rocket'), ('CRD', 'ATM Card'), ('PPL', 'PayPal')], default='COD', max_length=3),
        ),
    ]
