# Generated by Django 3.0.7 on 2020-07-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0006_order_delivery_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
