# Generated by Django 3.0.7 on 2020-07-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0007_order_order_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pharmacy_id',
        ),
    ]
