# Generated by Django 3.0.7 on 2020-07-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0008_remove_order_pharmacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pharmacy_id',
            field=models.ManyToManyField(to='medbot_app.Employee'),
        ),
    ]
