# Generated by Django 3.0.7 on 2020-09-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0011_auto_20200907_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_latiT',
            field=models.CharField(default='20.40', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_longT',
            field=models.CharField(default='90.40', max_length=20),
        ),
    ]
