# Generated by Django 3.1.1 on 2020-10-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0012_auto_20200907_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_carts',
            field=models.ManyToManyField(to='medbot_app.Cart'),
        ),
    ]
