# Generated by Django 3.1.1 on 2020-11-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0013_order_order_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_carts',
        ),
    ]
