# Generated by Django 3.1.1 on 2020-11-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0014_remove_order_order_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCart',
            fields=[
                ('order_cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adding_quantity', models.IntegerField(default=5)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.customer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.inventory')),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medbot_app.employee')),
            ],
        ),
    ]
