# Generated by Django 3.1.1 on 2020-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medbot_app', '0015_orderedcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orered_cart',
            field=models.ManyToManyField(to='medbot_app.OrderedCart'),
        ),
    ]
