from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about, name='about'),
    path('about-c', views.aboutC, name='aboutC'),
    path('about-e', views.aboutE, name='aboutE'),
    path('about-a', views.aboutA, name='aboutA'),
    path('login', views.loginC, name='loginC'),
    path('User', views.loginCustomer, name='loginCustomer'),
    path('logout', views.logoutC, name='logoutC'),
    path('register', views.registerC, name='registerC'),
    path('myaccount', views.settingsC, name='settingsC'),
    path('Admin-Page', views.loginA, name='adminpage'),
    path('Pharmacy', views.loginE, name='pharmacypage'),
    path('added/<list_id>', views.add_cart, name='add'),
    path('Cart', views.cart, name= 'cart'),
    path('user', views.customerPortal, name='customerx'),
    path('Checkout', views.checkoutOrder, name='checkoutC'),
    path('Add-item', views.addItemA, name='addItemA'),
    path('Pharmacy-Pending-Orders', views.orderHistoryE, name='orderHistoryE'),
    path('Pharmacy-Order-History', views.orderdetailsE, name='orderdetailsE'),
    path('Order', views.orderC, name= 'orderC'),
    path('User-Order-History', views.orderHistoryC, name='orderHistoryC'),
    path('Optimized-Route', views.opRouteE, name='opRouteE'),
    path('Profile-Saved', views.profileC, name='profileC'),
    path('catagories/<slug:foo>', views.catagorize, name= 'catagorize'),
    path('catagor-ies/<slug:food>', views.catagorizeC, name= 'catagorizeC'),
    path('removed/<list_id>', views.remv_cart, name='remv'),
    path('Upload-Prescription', views.prescript, name='prescriptC'),
    path('Order-Delivered/<list_id>', views.remvOrder, name= 'remvOrder'),
    path('Pharmacy-Profile', views.settingsE, name='settingsE'),
    path('Order-Details/<list_id>', views.orderDetails, name='orderDetails'),
    path('Order-Details-Customer/<list_id>', views.orderDetailsC, name='orderDetailsC'),
    path('Minus-Cart/<list_id>', views.minusCart, name='minusCart'),
    path('Addup-Cart/<list_id>', views.addupCart, name='addupCart'),
]
